### PR TITLE
Tei xml download

### LINKED ISSUE #166: Export of published XML
There needs to be a URL where one can access the concatenated export of all the published leaves into a single valid TEI XML document.

### PR DESCRIPTION
**Pull request by timdunn22**
Closes #166

### CODE REVIEW

**Comment by timdunn22** [comment]
@jamiefolsom I need some clarification on this. In the comment above I am told that the xml needs to be verified but when I go to the site recommended I am not sure what that looks like.

**Comment by jamiefolsom** [comment]
@timdunn22 per our chat today, the TEI XML that's exported is still not valid. Once that's addressed, I believe this will be complete.

**Comment by timdunn22** [comment]
## What does this issue do?
1. Allows users to download tea xml document

## How to test?
1. Login and go to https://mel-textlab.herokuapp.com/
2. Click on edit for any given project you own (If you don’t own one make one)
3. Click on edit settings
4. Click on Export XML
5. Go to http://teibyexample.org/xquery/TBEvalidator.xq and upload and your file and click on validate
6. There should be no validation errors

**Comment by SteveMarvin** [comment]
Error in validation:

exerr:EXXQDY0002 Document is not valid. Fatal (5215,3) : The element type "body" must be terminated by the matching end-tag "</body>". Validated in -1 millisec. [at line 84, column 10, source: /db/apps/TBE/TBE_site/xquery/TBEvalidator.xql]

**Pull request merged**
